version: '3.8'
services:
  db:
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    volumes:
      - "./data:/var/lib/postgresql/data"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      - POSTGRES_PASSWORD=pwd
      - POSTGRES_USER=user
      - POSTGRES_DB=postgres